const heading = React.createElement('h1', { id: 'title', className: "woho" }, 'Hello From Shubham')
const heading1 = React.createElement('h1', { id: 'title2', className: "woho2" }, 'Hello From Simran')
const container = React.createElement('div', { id: 'container' }, [heading, heading1])
const root = ReactDOM.createRoot(document.getElementById('root'))
root.render(container)